# Site settings
title: Rantt
email: info@sesolutions.net.au
description: "Resource Gantt"
url: http://resourcegantt.azurewebsites.net/
include: [_colorpicker.js, _handlebars.js, _jquery.placeholder.js, _scripts.js, _jq.js, _skinchooser.js, _skins.js, _colorpicker.css]

# Build settings
markdown: kramdown
permalink: pretty
destination: ./website