# Site settings
title: Rantt is a Resource Gantt Chart desktop application
email: contact@wildgums.com
description: "Rantt is a Resource Gantt chart application used to visualize shop floor data from factories or schedules"
url: http://www.resourcegantt.com
logo: /images/rantt-logo.png
author: WildGums
include: [_colorpicker.js, _handlebars.js, _jquery.placeholder.js, _scripts.js, _jq.js, _skinchooser.js, _skins.js, _colorpicker.css]
exclude: [vendor]

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
